# Generated by Django 4.2.1 on 2023-07-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resetpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetPassword',
            new_name='ForgotPassword',
        ),
    ]
